"""add amount to orders

Revision ID: 3044086c588e
Revises: 9dd4753dc7b5
Create Date: 2026-06-15 12:25:53.076198

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3044086c588e"
down_revision: str | Sequence[str] | None = "9dd4753dc7b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders_v2",
        sa.Column("amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders_v2", "amount")
    # ### end Alembic commands ###
