"""change idempotency_key to string

Revision ID: 9dd4753dc7b5
Revises: 6774f37f3977
Create Date: 2026-06-11 15:22:09.482896

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9dd4753dc7b5"
down_revision: str | Sequence[str] | None = "6774f37f3977"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
